# Generated by Django 3.0.5 on 2020-12-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='call_attr',
            field=models.CharField(blank=True, choices=[('call', '상담전화했음'), ('bad', '진상고객'), ('customer', '계약함')], max_length=80, null=True),
        ),
    ]
