# Generated by Django 3.1.4 on 2020-12-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20201222_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='call_attr',
            field=models.CharField(blank=True, choices=[('wrong', '잘못된DB'), ('call', '상담전화했음'), ('customer', '계약함'), ('bad', '진상고객')], max_length=80, null=True, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='information',
            name='check_call',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='DB중복여부'),
        ),
        migrations.AlterField(
            model_name='information',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='날짜'),
        ),
    ]
