# Generated by Django 2.2.4 on 2021-01-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20201222_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='name',
        ),
        migrations.AlterField(
            model_name='information',
            name='call_attr',
            field=models.CharField(blank=True, choices=[('call', '상담전화했음'), ('wrong', '잘못된DB'), ('customer', '계약함'), ('bad', '진상고객')], max_length=80, null=True, verbose_name='상태'),
        ),
    ]
