# Generated by Django 2.2.4 on 2021-01-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210108_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='call_attr',
            field=models.CharField(blank=True, choices=[('bad', '진상고객'), ('wrong', '잘못된DB'), ('call', '상담전화했음'), ('customer', '계약함')], max_length=80, null=True, verbose_name='상태'),
        ),
    ]
